### ISSUE TITLE
missing function f2g

### ISSUE THREAD

**Issue by ydurand** [jrmuizel/pyunum#2]
Hello,
 while debugging an very hazardous code i encountered this error:
f2g is not defined in the module (no revision number). This produces this error

  File "unum.py", line 1018, in squareg
    return f2g(float('nan'))
NameError: global name 'f2g' is not defined

However, it is only used with 'nan' as argument -> there may be a good reason to this..
best regards,
Yves

**Comment by jrmuizel** [comment]
Should be fixed by 7b43c152960d6d6820ab4178dbeeecc3a4222e57
