### ISSUE TITLE
Quadrants in timesg and divideg

### ISSUE THREAD

**Issue by jimon** [jrmuizel/pyunum#4]
I'm really confused in one moment there : `(xlo < 0 or (xlo == 0 and not xlob))` - what does it actually mean ? `xlo < 0` - ok, this is "xlo is strictly negative", and `xlo == 0 and not xlob` this is "xlo is strictly zero" ... and last one confuses me a lot.

Why we want to cover only [-inf, -ulp] & 0 without including [-inf, 0) ? I've checked the book - it's a same there.

**Comment by jrmuizel** [comment]
Good question. I don't have an immediate answer.

**Comment by jimon** [comment]
Asked John Gustafson himself, so the answer is :

`if you check the range [-inf, -ulp] as a _left_ endpoint, then you have covered every possible unum that has a strictly negative endpoint. There are no unums with left endpoints in (-ulp, 0) if the "ulp" is the smallest ulp possible in the unum environment. If the left endpoint of a unum is -ulp and the unum is inexact, then the right endpoint of the unum is zero (and is an open interval endpoint).`
